name: Release EXE files

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build EXEs
        run: |
          pyinstaller --onefile encryption.py
          pyinstaller --onefile decryption.py
        working-directory: .

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/encryption.exe
            dist/decryption.exe
