name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write  # Needed for creating releases and uploading assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build encryption.exe
        run: pyinstaller encryption.py --onefile --name encryption

      - name: Build decryption.exe
        run: pyinstaller decryption.py --onefile --name decryption

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automatic release generated by GitHub Actions.

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/encryption.exe
            dist/decryption.exe
